vim.o.number = true
vim.o.relativenumber = true
vim.o.cursorline = true
vim.o.tabstop = 4
vim.o.smarttab = true
vim.o.shiftwidth = 4
vim.o.softtabstop = 4
--vim.o.list = true
-- vim.o.listchars = 'tab:|\\ ,trail:▫'
